document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\"en\">");
document.writeln("<head>");
document.writeln("    <meta charset=\"UTF-8\">");
document.writeln("    <title>back to top with anime</title>");
document.writeln("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/btt.css\">");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <div id=\"box\" class=\"box\">");
document.writeln("        <div class=\"box-in\"></div>");
document.writeln("    </div>");
document.writeln("    <script>");
document.writeln("    var timer  = null;");
document.writeln("    box.onclick = function(){");
document.writeln("        cancelAnimationFrame(timer);");
document.writeln("        //获取当前毫秒数");
document.writeln("        var startTime = +new Date();");
document.writeln("        //获取当前页面的滚动高度");
document.writeln("        var b = document.body.scrollTop || document.documentElement.scrollTop;");
document.writeln("        var d = 500;");
document.writeln("        var c = b;");
document.writeln("        timer = requestAnimationFrame(function func(){");
document.writeln("            var t = d - Math.max(0,startTime - (+new Date()) + d);");
document.writeln("            document.documentElement.scrollTop = document.body.scrollTop = t * (-c) / d + b;");
document.writeln("            timer = requestAnimationFrame(func);");
document.writeln("            if(t == d){");
document.writeln("            cancelAnimationFrame(timer);");
document.writeln("            }");
document.writeln("        });");
document.writeln("    }");
document.writeln("    </script>");
document.writeln("</body>");
document.writeln("</html>");