document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\"en\">");
document.writeln("<head>");
document.writeln("<meta charset=\"UTF-8\">");
document.writeln("<title>Document</title>");
document.writeln("<style>");
document.writeln(".box{");
document.writeln("    position:fixed;");
document.writeln("    right:10px;");
document.writeln("    bottom: 10px;");
document.writeln("    height:30px;");
document.writeln("    width: 50px;    ");
document.writeln("    text-align:center;");
document.writeln("    padding-top:20px;    ");
document.writeln("    background-color: lightblue;");
document.writeln("    border-radius: 20%;");
document.writeln("    overflow: hidden;");
document.writeln("}");
document.writeln(".box:hover:before{");
document.writeln("    top:50%");
document.writeln("}");
document.writeln(".box:hover .box-in{");
document.writeln("    visibility: hidden;");
document.writeln("}");
document.writeln(".box:before{");
document.writeln("    position: absolute;");
document.writeln("    top: -50%;");
document.writeln("    left: 50%;");
document.writeln("    transform: translate(-50%,-50%);");
document.writeln("    content:\'top\';");
document.writeln("    width: 40px;");
document.writeln("    color:peru;");
document.writeln("    font-weight:bold;");
document.writeln("");
document.writeln("}    ");
document.writeln(".box-in{");
document.writeln("    visibility: visible;");
document.writeln("    display:inline-block;");
document.writeln("    height:20px;");
document.writeln("    width: 20px;");
document.writeln("    border: 3px solid black;");
document.writeln("    border-color: white transparent transparent white;");
document.writeln("    transform:rotate(45deg);");
document.writeln("}");
document.writeln("</style>");
document.writeln("</head>");
document.writeln("<body style=\"height:2000px;\">");
document.writeln("<div id=\"box\" class=\"box\">");
document.writeln("    <div class=\"box-in\"></div>");
document.writeln("</div>    ");
document.writeln("<script>");
document.writeln("var timer  = null;");
document.writeln("box.onclick = function(){");
document.writeln("    cancelAnimationFrame(timer);");
document.writeln("    //获取当前毫秒数");
document.writeln("    var startTime = +new Date();     ");
document.writeln("    //获取当前页面的滚动高度");
document.writeln("    var b = document.body.scrollTop || document.documentElement.scrollTop;");
document.writeln("    var d = 500;");
document.writeln("    var c = b;");
document.writeln("    timer = requestAnimationFrame(function func(){");
document.writeln("        var t = d - Math.max(0,startTime - (+new Date()) + d);");
document.writeln("        document.documentElement.scrollTop = document.body.scrollTop = t * (-c) / d + b;");
document.writeln("        timer = requestAnimationFrame(func);");
document.writeln("        if(t == d){");
document.writeln("          cancelAnimationFrame(timer);");
document.writeln("        }");
document.writeln("    });");
document.writeln("}");
document.writeln("</script>");
document.writeln("</body>");
document.writeln("</html>");