document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\"en\">");
document.writeln("<head>");
document.writeln("    <meta charset=\"UTF-8\">");
document.writeln("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">");
document.writeln("    <title>header</title>");
document.writeln("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/header.css\">");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <nav class=\"menu\">");
document.writeln("        <ul>");
document.writeln("            <li> <a href=\"index1.html\">首页</a> </li>");
document.writeln("            <li> <a href=\"classpublic.html\">班级公告</a> </li>");
document.writeln("            <li> <a href=\"classblog.html\">班级日志</a> </li>");
document.writeln("            <li> <a href=\"classphoto.html\">班级相册</a> </li>");
document.writeln("            <li> <a href=\"https://starsky.earth/\"  target=\"_blank\" >个人主页</a> </li>");
document.writeln("            <li> <a href=\"back.html\" target=\"_blank \">留言板</a> </li>");
document.writeln("            <li> <a href=\"aboutus.html\">关于我们</a> </li>");
document.writeln("        </ul>");
document.writeln("    </nav>");
document.writeln("</body>");
document.writeln("</html>");