document.writeln("<!DOCTYPE html>");
document.writeln("<html lang=\"en\">");
document.writeln("<head>");
document.writeln("    <meta charset=\"UTF-8\">");
document.writeln("    <link rel=\"stylesheet\" type=\"text/css\" href=\"../css/mia.css\">");
document.writeln("    <title>menu in air</title>");
document.writeln("</head>");
document.writeln("<body>");
document.writeln("    <div class=\"action\" onclick=\"actionToggle();\">");
document.writeln("        <span>+</span>");
document.writeln("        <ul>");
document.writeln("            <li> <a href=\"index1.html\">首页</a> </li>");
document.writeln("            <li> <a href=\"classpublic.html\">班级公告</a> </li>");
document.writeln("            <li> <a href=\"classblog.html\">班级日志</a> </li>");
document.writeln("            <li> <a href=\"classphoto.html\">班级相册</a> </li>");
document.writeln("            <li> <a href=\"https://starsky.earth/\"  target=\"_blank\" >个人主页</a> </li>");
document.writeln("            <li> <a href=\"back.html\" target=\"_blank \">留言板</a> </li>");
document.writeln("            <li> <a href=\"aboutus.html\">关于我们</a> </li>");
document.writeln("        </ul>");
document.writeln("    </div>");
document.writeln("    <script type=\"text/javascript\">");
document.writeln("        function actionToggle(){");
document.writeln("            var action = document.querySelector(\'.action\');");
document.writeln("            action.classList.toggle(\'active\')");
document.writeln("        }");
document.writeln("    </script>");
document.writeln("</body>");
document.writeln("</html>");